Try adding a dummy  step to make jobs required

diff --git a/.github/workflows/test_e2e_portal.yml b/.github/workflows/test_e2e_portal.yml
--- a/.github/workflows/test_e2e_portal.yml
+++ b/.github/workflows/test_e2e_portal.yml
@@ -23,7 +23,7 @@ env:
   e2eTestsPath: './e2e'
 
 jobs:
-  test:
+  test_e2e_portal:
     runs-on: ubuntu-latest
     environment: test
 
@@ -110,3 +110,17 @@ jobs:
       - name: Docker logs
         if: always()
         uses: jwalton/gh-docker-logs@v2
+
+  # This job is here to make the above jobs "required" in GitHub, because
+  # we have informed GitHub that all `test` jobs are required.
+  # This is a workaround for this issue: https://github.com/orgs/community/discussions/44490
+  test:
+    runs-on: ubuntu-latest
+    needs: [test_e2e_portal]
+    if: ${{ always() }}
+    steps:
+      - name: Required check failed
+        if: ${{ contains(needs.*.result, 'failure') }}
+        run: exit 1
+      - name: Dummy step
+        run: echo "All required checks have successfully passed."
diff --git a/.github/workflows/test_service_api.yml b/.github/workflows/test_service_api.yml
--- a/.github/workflows/test_service_api.yml
+++ b/.github/workflows/test_service_api.yml
@@ -153,3 +153,17 @@ jobs:
           files: coverage/**/lcov.info
           verbose: true
           skip-errors: false
+
+  # This job is here to make the above jobs "required" in GitHub, because
+  # we have informed GitHub that all `test` jobs are required.
+  # This is a workaround for this issue: https://github.com/orgs/community/discussions/44490
+  test:
+    runs-on: ubuntu-latest
+    needs: [test_integration, test_static_checks]
+    if: ${{ always() }}
+    steps:
+      - name: Required check failed
+        if: ${{ contains(needs.*.result, 'failure') }}
+        run: exit 1
+      - name: Dummy step
+        run: echo "All required checks have successfully passed."
