chore: add test-shard-resolution (#7047)
* chore: add test-shard-resolution

AB#37295

* give resolution steps different nams

diff --git a/.github/workflows/test_e2e_portal.yml b/.github/workflows/test_e2e_portal.yml
--- a/.github/workflows/test_e2e_portal.yml
+++ b/.github/workflows/test_e2e_portal.yml
@@ -128,3 +128,16 @@ jobs:
       - name: Docker logs
         if: always()
         uses: jwalton/gh-docker-logs@v2
+
+  # This job is here to make the above jobs "required" in GitHub.
+  # This is a workaround for this issue: https://github.com/orgs/community/discussions/44490
+  test-shard-resolution-e2e:
+    runs-on: ubuntu-latest
+    needs: [test-shard]
+    if: ${{ always() }}
+    steps:
+      - name: Required check failed
+        if: ${{ contains(needs.*.result, 'failure') }}
+        run: exit 1
+      - name: Dummy step
+        run: echo "All required checks have successfully passed."
