fix: Prevent false-positives when canceling a test-run

diff --git a/.github/workflows/test_e2e_portal.yml b/.github/workflows/test_e2e_portal.yml
--- a/.github/workflows/test_e2e_portal.yml
+++ b/.github/workflows/test_e2e_portal.yml
@@ -139,8 +139,13 @@ jobs:
     needs: [test-shard]
     if: ${{ always() }}
     steps:
-      - name: Required check failed
+      - name: Check required job results
         if: ${{ contains(needs.*.result, 'failure') }}
-        run: exit 1
-      - name: Dummy step
-        run: echo "All required checks have successfully passed."
+        run: |
+          echo "Some checks have failed." >> $GITHUB_STEP_SUMMARY
+          exit 1
+      - name: Check required job results
+        if: ${{ contains(needs.*.result, 'failure') != 'true' || contains(needs.*.result, 'cancelled') != 'true' || contains(needs.*.result, 'skipped') != 'true' }}
+        run: |
+          echo "All required checks have successfully passed." >> $GITHUB_STEP_SUMMARY
+          exit 0
