chore: revert combined coverage in CI + shard integration tests (#7019)
* chore: coverage updates

* Update services/121-service/README.md

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

* Try adding 'shardCount' to the matrix.

* Try adding a dummy  step to make jobs required

---------

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

diff --git a/.github/workflows/test_e2e_portal.yml b/.github/workflows/test_e2e_portal.yml
--- a/.github/workflows/test_e2e_portal.yml
+++ b/.github/workflows/test_e2e_portal.yml
@@ -23,15 +23,15 @@ env:
   e2eTestsPath: './e2e'
 
 jobs:
-  test:
+  test_e2e_portal:
     runs-on: ubuntu-latest
     environment: test
 
     strategy:
       fail-fast: false
       matrix:
-        # if you change the number of shards, you must also change the denominator accordingly in the `--shard` option below
         shard: ['1', '2', '3', '4', '5', '6']
+        shardCount: ['6']
 
     steps:
       - name: Check out repository code
@@ -92,7 +92,7 @@ jobs:
         env:
           BASE_URL: http://localhost:8088
         run: |
-          npm test -- --shard=${{ matrix.shard }}/6
+          npm test -- --shard=${{ matrix.shard }}/${{ matrix.shardCount }}
 
       - uses: actions/upload-artifact@v4
         if: always()
@@ -110,3 +110,17 @@ jobs:
       - name: Docker logs
         if: always()
         uses: jwalton/gh-docker-logs@v2
+
+  # This job is here to make the above jobs "required" in GitHub, because
+  # we have informed GitHub that all `test` jobs are required.
+  # This is a workaround for this issue: https://github.com/orgs/community/discussions/44490
+  test:
+    runs-on: ubuntu-latest
+    needs: [test_e2e_portal]
+    if: ${{ always() }}
+    steps:
+      - name: Required check failed
+        if: ${{ contains(needs.*.result, 'failure') }}
+        run: exit 1
+      - name: Dummy step
+        run: echo "All required checks have successfully passed."
