ci: Make the path-filter external-action only run on PRs, to prevent confusing errors (#7050)
* ci: Make the external path-filter action only run on PRs, to avoid confusing errors

* fix: Prevent false-positives when canceling a test-run

* refactor: Prevent more action on non-PR-runs

* Apply suggestions from code review

Co-authored-by: Domenico Gemoli <dgemoli@redcross.nl>

* fix: Align requirements checks

* fix: Align both test-runs in "path-filter"-behaviour

---------

Co-authored-by: Domenico Gemoli <dgemoli@redcross.nl>

diff --git a/.github/workflows/test_e2e_portal.yml b/.github/workflows/test_e2e_portal.yml
--- a/.github/workflows/test_e2e_portal.yml
+++ b/.github/workflows/test_e2e_portal.yml
@@ -20,15 +20,19 @@ jobs:
     outputs:
       should_skip: ${{ steps.filter.outputs.should_skip }}
     steps:
-      - uses: actions/checkout@v4 # better this action use git diff, so you need checkout the code first
+      - uses: actions/checkout@v4
+        # Other events (from the merge-queue) can safely ignore the path-filter; Its output would default to 'NOT true'
+        if: github.event_name == 'pull_request'
         with:
-          filter: blob:none # reduce clone size
-          fetch-depth: 0 # need full history, the default is 1, which is not enough. if you limit the pull request' commit length, you can set it to your limit.
-      - uses: leavesster/pull-request-path-filter@v0.2 # v0.2 is the latest version
-        id: 'filter'
+          filter: blob:none # Reduce clone size/speed
+          fetch-depth: 0 # Full history is needed to determine the "changed files in this PR"
+
+      - uses: leavesster/pull-request-path-filter@v0.2
+        # Other events (from the merge-queue) can safely ignore the path-filter; Its output would default to 'NOT true'
+        if: github.event_name == 'pull_request'
+        id: filter
         with:
-          paths:
-            | # notice the `|`, it's required. the left is same as github action's path and paths-ignore
+          paths: |
             - '.github/workflows/test_e2e_portal.yml'
             - 'e2e/**'
             - 'services/.env.example'
@@ -39,6 +43,7 @@ jobs:
             - '!interfaces/portal/**.test.ts'
             - '!interfaces/portal/**.spec.ts'
             - '!**.md'
+
   test-shard:
     runs-on: ubuntu-latest
     needs: path-filter
@@ -134,10 +139,15 @@ jobs:
   test-shard-resolution-e2e:
     runs-on: ubuntu-latest
     needs: [test-shard]
-    if: ${{ always() }}
+    if: always()
     steps:
-      - name: Required check failed
-        if: ${{ contains(needs.*.result, 'failure') }}
-        run: exit 1
-      - name: Dummy step
-        run: echo "All required checks have successfully passed."
+      - name: Check required job results
+        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+        run: |
+          echo "Some checks have failed." >> $GITHUB_STEP_SUMMARY
+          exit 1
+      - name: Check required job results
+        if: contains(needs.*.result, 'failure') != 'true' || contains(needs.*.result, 'cancelled') != 'true'
+        run: |
+          echo "All required checks have successfully passed." >> $GITHUB_STEP_SUMMARY
+          exit 0
